### ISSUE TITLE
[Done] OOM issue when train 1.5B PPO on 4 * A100 80G

### ISSUE THREAD

**Issue by liuchengyuan123** [Open-Reasoner-Zero/Open-Reasoner-Zero#24]
Hello, I have tried to reproduce the experiment of PPO using Qwen2.5-1.5B model, because I don't have many GPUs.
I use 4 * A100 80G GPUs.
All modifications are listed as following:
1. `total_num_nodes: int = 4`
2. `pretrain: Optional[str] = "xxx/Qwen2.5-1.5B"`
3. `rollout_batch_size` and `micro_rollout_batch_size` are both set as 2
4. I change all variables refering to the sequence length to smaller size, such as 1k.

However, I still got the following error:
```bash
(CriticRayActorBase pid=2004874) [2025-02-22 21:53:45,813] [INFO] [config.py:1003:print]   zero_enabled ................. True
(CriticRayActorBase pid=2004874) [2025-02-22 21:53:45,813] [INFO] [config.py:1003:print]   zero_force_ds_cpu_optimizer .. True
(CriticRayActorBase pid=2004874) [2025-02-22 21:53:45,813] [INFO] [config.py:1003:print]   zero_optimization_stage ...... 3
(CriticRayActorBase pid=2004874) [2025-02-22 21:53:45,813] [INFO] [config.py:989:print_user_config]   json = {
(CriticRayActorBase pid=2004874)     "steps_per_print": 100, 
(CriticRayActorBase pid=2004874)     "zero_optimization": {
(CriticRayActorBase pid=2004874)         "stage": 3, 
(CriticRayActorBase pid=2004874)         "offload_param": {
(CriticRayActorBase pid=2004874)             "device": "none"
(CriticRayActorBase pid=2004874)         }, 
(CriticRayActorBase pid=2004874)         "offload_optimizer": {
(CriticRayActorBase pid=2004874)             "device": "none", 
(CriticRayActorBase pid=2004874)             "pin_memory": true
(CriticRayActorBase pid=2004874)         }, 
(CriticRayActorBase pid=2004874)         "sub_group_size": "auto", 
(CriticRayActorBase pid=2004874)         "stage3_max_live_parameters": "auto", 
(CriticRayActorBase pid=2004874)         "stage3_max_reuse_distance": "auto", 
(CriticRayActorBase pid=2004874)         "stage3_param_persistence_threshold": "auto", 
(CriticRayActorBase pid=2004874)         "stage3_prefetch_bucket_size": "auto", 
(CriticRayActorBase pid=2004874)         "reduce_bucket_size": "auto", 
(CriticRayActorBase pid=2004874)         "zero_hpz_partition_size": 1, 
(CriticRayActorBase pid=2004874)         "zero_quantized_weights": false, 
(CriticRayActorBase pid=2004874)         "zero_quantized_gradients": false
(CriticRayActorBase pid=2004874)     }, 
(CriticRayActorBase pid=2004874)     "bf16": {
(CriticRayActorBase pid=2004874)         "enabled": true
(CriticRayActorBase pid=2004874)     }, 
(CriticRayActorBase pid=2004874)     "gradient_clipping": 1.0, 
(CriticRayActorBase pid=2004874)     "prescale_gradients": false, 
(CriticRayActorBase pid=2004874)     "wall_clock_breakdown": false, 
(CriticRayActorBase pid=2004874)     "data_types": {
(CriticRayActorBase pid=2004874)         "grad_accum_dtype": "fp32"
(CriticRayActorBase pid=2004874)     }, 
(CriticRayActorBase pid=2004874)     "train_micro_batch_size_per_gpu": 1, 
(CriticRayActorBase pid=2004874)     "gradient_accumulation_steps": 1
(CriticRayActorBase pid=2004874) }
2025-02-22 21:53:47.340 | INFO     | orz.ppo.trainer:build_models:728 - init policy/ref/critic/reward models done
Traceback (most recent call last):
  File "xxx/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "xxx/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "Open-Reasoner-Zero/playground/orz_7b_ppo.py", line 570, in <module>
    asyncio.run(exp.run())
  File "xxx/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "xxx/lib/python3.10/asyncio/base_events.py", line 649, in run_until_complete
    return future.result()
  File "Open-Reasoner-Zero/orz/exps/examples/ppo/ppo_base_exp.py", line 231, in run
    await self.trainer.train()
  File "Open-Reasoner-Zero/orz/ppo/trainer.py", line 70, in train
    await self._backload_vllm_engines()
  File "Open-Reasoner-Zero/orz/ppo/trainer.py", line 1289, in _backload_vllm_engines
    await asyncio.gather(*backload_tasks)
  File "xxx/lib/python3.10/asyncio/tasks.py", line 650, in _wrap_awaitable
    return (yield from awaitable.__await__())
ray.exceptions.RayTaskError(OutOfMemoryError): ray::LLMActor.backload_to_gpu() (pid=2003691, ip=10.32.9.130, actor_id=4dd4449826a83dd6162d045201000000, repr=<orz.exp_engine.accelerators.inference.vllm_engine.LLMActor object at 0x7fdf0c4b9720>)
  File "Open-Reasoner-Zero/orz/exp_engine/accelerators/inference/vllm_engine.py", line 76, in backload_to_gpu
    self.llm.llm_engine.model_executor.driver_worker.load_gpu()
  File "Open-Reasoner-Zero/orz/exp_engine/accelerators/inference/vllm_worker_wrap.py", line 100, in load_gpu
    super()._init_cache_engine()
  File "Open-Reasoner-Zero/python/openrlhf/lib/python3.10/site-packages/vllm/worker/worker.py", line 311, in _init_cache_engine
    self.cache_engine = [
  File "Open-Reasoner-Zero/python/openrlhf/lib/python3.10/site-packages/vllm/worker/worker.py", line 312, in <listcomp>
    CacheEngine(self.cache_config, self.model_config,
  File "Open-Reasoner-Zero/python/openrlhf/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 69, in __init__
    self.gpu_cache = self._allocate_kv_cache(
  File "Open-Reasoner-Zero/python/openrlhf/lib/python3.10/site-packages/vllm/worker/cache_engine.py", line 103, in _allocate_kv_cache
    layer_kv_cache = torch.zeros(alloc_shape,
torch.OutOfMemoryError: CUDA out of memory. Tried to allocate 1.30 GiB. GPU 0 has a total capacity of 79.35 GiB of which 278.19 MiB is free. Process 2451163 has 67.49 GiB memory in use. Process 2452744 has 5.58 GiB memory in use. Process 2453282 has 2.77 GiB memory in use. Process 2453721 has 3.21 GiB memory in use. Of the allocated memory 66.85 GiB is allocated by PyTorch, and 148.04 MiB is reserved by PyTorch but unallocated. If reserved but unallocated memory is large try setting PYTORCH_CUDA_ALLOC_CONF=expandable_segments:True to avoid fragmentation.  See documentation for Memory Management  (https://pytorch.org/docs/stable/notes/cuda.html#environment-variables)
(CriticRayActorBase pid=2005241) The argument `trust_remote_code` is to be used with Auto classes. It has no effect here and is ignored. [repeated 3x across cluster]
(CriticRayActorBase pid=2005241) Using /root/.cache/torch_extensions/py310_cu124 as PyTorch extensions root... [repeated 4x across cluster]
(CriticRayActorBase pid=2005242) Loading extension module fused_adam... [repeated 4x across cluster]
(CriticRayActorBase pid=2005241) You are attempting to use Flash Attention 2.0 with a model not initialized on GPU. Make sure to move the model to GPU after initializing it on CPU with `model.to('cuda')`. [repeated 3x across cluster]
(CriticRayActorBase pid=2005241) Some weights of CriticModel were not initialized from the model checkpoint at ../open-r1/hf-models/Qwen2.5-1.5B and are newly initialized: ['value_head.weight'] [repeated 3x across cluster]
(CriticRayActorBase pid=2005241) You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference. [repeated 3x across cluster]
(CriticRayActorBase pid=2005241) 2025-02-22 21:53:42.343 | INFO     | orz.ppo.models:get_llm_for_sequence_regression:572 - initialize value_head for ZeRO-3 reward model training. [repeated 3x across cluster]
```

**Comment by liuchengyuan123** [comment]
Key Environments:
CUDA 12.4

accelerate                        1.4.0
async-timeout                     5.0.1
bitsandbytes                      0.45.2
datasets                          3.3.2
deepspeed                         0.16.3
flash-attn                        2.7.0.post2
huggingface-hub                   0.29.1
hydra-core                        1.3.2
jinja2                            3.1.5
jsonlines                         4.0.0
jsonschema                        4.23.0
jsonschema-specifications         2024.10.1
loguru                            0.7.3
loralib                           0.1.2
modelscope                        1.23.1
numpy                             1.26.4
nvidia-cublas-cu12                12.4.5.8
nvidia-cuda-cupti-cu12            12.4.127
nvidia-cuda-nvrtc-cu12            12.4.127
nvidia-cuda-runtime-cu12          12.4.127
nvidia-cudnn-cu12                 9.1.0.70
nvidia-cufft-cu12                 11.2.1.3
nvidia-curand-cu12                10.3.5.147
nvidia-cusolver-cu12              11.6.1.9
nvidia-cusparse-cu12              12.3.1.170
nvidia-cusparselt-cu12            0.6.2
nvidia-ml-py                      12.570.86
nvidia-nccl-cu12                  2.21.5
nvidia-nvjitlink-cu12             12.4.127
nvidia-nvtx-cu12                  12.4.127
omegaconf                         2.3.0
openai                            1.63.2
opencv-python-headless            4.11.0.86
optimum                           1.24.0
orz                               0.1.0
pandas                            2.2.3
peft                              0.14.0
pillow                            11.1.0
pip                               25.0.1
pydantic                          2.10.6
pydantic-core                     2.27.2
ray                               2.42.0
regex                             2024.11.6
safetensors                       0.5.2
sentencepiece                     0.2.0
setuptools                        75.8.0
tensorboard                       2.19.0
tensorboard-data-server           0.7.2
tensorboardx                      2.6.2.2
tiktoken                          0.9.0
tokenizers                        0.21.0
torch                             2.5.1
torchaudio                        2.5.1
torchmetrics                      1.6.1
torchvision                       0.20.1
tqdm                              4.67.1
transformers                      4.48.3
transformers-stream-generator     0.0.5
triton                            3.1.0
trl                               0.15.1
typing-extensions                 4.12.2
tzdata                            2025.1
vllm                              0.7.2
wandb                             0.19.7
xformers                          0.0.28.post3

**Comment by REIGN12** [comment]
Many thanks for you attention! 
Can you please provide the detailed logging for the parameters of your experiments?
I hypothesize this is because `gpu_memory_utilization` are set too high, you can try something like 0.5 at first to test whether it can be run.

**Comment by REIGN12** [comment]
We will soon provide our reference settings for 1.5B zero experiments. And we will update in this thread as this is ready. Please stay tuned!

**Comment by liuchengyuan123** [comment]
> Many thanks for you attention! Can you please provide the detailed logging for the parameters of your experiments? I hypothesize this is because `gpu_memory_utilization` are set too high, you can try something like 0.5 at first to test whether it can be run.

I really appreciate your patient response! This solves the problem.
